#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,math,sys,inspect
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'research/shadow'))
from rtk_c10_65s5d_branch_builder import build
from rtk_c10_65s2c_current_state_dae_metric_core import current_state_metric_core
from rtk_c10_65s2d_current_state_traceless_tca_closure import current_state_traceless_tca
from rtk_c10_65s2e_current_state_derivative_slip_closure import dynamic_derivative_slip
def L(p):return json.loads((ROOT/p).read_text())
def rel(a,b):a=float(a);b=float(b);return abs(a-b)/max(abs(a),abs(b),1e-300)
def finite(x):return math.isfinite(float(x))
def parse(path):
 rows=[];ns=['phi','delta_b','theta_b','delta_g','theta_g','delta_ur','theta_ur','shear_ur','delta_khr_N','theta_khr_N'];nd=['phi_prime','delta_b_prime','theta_b_prime','delta_g_prime','theta_g_prime','delta_ur_prime','theta_ur_prime','delta_khr_N_prime','theta_khr_N_prime'];nk=['B','B_prime','psi_pref','psi_pref_prime','phi_pref','Psi_N','Psi_N_prime','Phi_N','sigma_g','tca_slip'];nr=['A_raw','A_norm','H_raw','H_norm','M_raw','M_norm','T_raw','T_norm','feedback_denominator','implicit_denominator']
 for line in Path(path).read_text().splitlines():
  if not line.strip():continue
  p=line.strip().split(',');assert len(p)==63,(path,len(p));r={'phase':p[0],'tau':float(p[1]),'a':float(p[2]),'k':float(p[3]),'tca':int(p[4]),'rsa':int(p[5]),'ufa':int(p[6]),'lmax':int(p[7]),'rhs_calls':int(p[8])};j=9
  for n in ns:r[n]=float(p[j]);j+=1
  for n in nd:r[n]=float(p[j]);j+=1
  for n in nk:r[n]=float(p[j]);j+=1
  for n in nr:r[n]=float(p[j]);j+=1
  r['Fl']={l:float(p[j+l-3]) for l in range(3,18)};rows.append(r)
 return rows
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--observer-dir',required=True);ap.add_argument('--off-identity',required=True);ap.add_argument('--patch',required=True);ap.add_argument('--output',required=True);a=ap.parse_args();t=L('research/theory_targets/RTK_C10_65S5D_NEXT_K_MULTIBRANCH_ONE_STEP_PRODUCTION_CANARY_TARGET_v1.json');s5a=L('research/theory_results/RTK_C10_65S5A_NEXT_K_NEAR_HORIZON_ONSET_STATE_PREFLIGHT_RESULT_v1.json');s5b=L('research/theory_results/RTK_C10_65S5B_NEXT_K_COMPLETED_ONSET_SEED_DOMAIN_AUDIT_RESULT_v1.json');s5c=L('research/theory_results/RTK_C10_65S5C_NEXT_K_OMITTED_ORDER_SENSITIVITY_RESULT_v1.json');s2k=L('research/theory_results/RTK_C10_65S2K_ONE_ACCEPTED_STEP_RETRY_RESULT_v1.json');s2e=L('research/theory_results/RTK_C10_65S2E_CURRENT_STATE_DERIVATIVE_SLIP_CLOSURE_RESULT_v1.json');s2b=L('research/theory_results/RTK_C10_65S2B_NEWTONIAN_KHRONON_RHS_BRIDGE_RESULT_v1.json');f=L('research/theory_results/RTK_C10_65F_TCA_DOMAIN_PARTITION_EXACT_ONSET_PACK_RESULT_v1.json');cur=L('research/state/current.json')
 assert t['status']=='FROZEN_BEFORE_IMPLEMENTATION';assert s5a['classification']==t['parents']['C10.65s5a'];assert s5b['classification']==t['parents']['C10.65s5b'];assert s5c['classification']==t['parents']['C10.65s5c'];assert s2k['classification']==t['parents']['C10.65s2k'];assert s2e['classification']==t['parents']['C10.65s2e_historical']
 bg=build('baseline')['background'];aa=float(bg['a']);H=float(bg['H']);rb=float(bg['rhob']);rg=float(bg['rhog']);ru=float(bg['rhour']);rk=float(bg['rho_khr']);pk=float(bg['p_khr']);pack=f['coefficient_pack'];cb2=float(pack['cb2']);tau=float(pack['tau_c_Mpc']);dtau=float(pack['dtau_c']);Hps=[float(q['Hc_prime_reconstructed']) for q in s2b['records']];Hp=sum(Hps)/len(Hps);lamD=float(cur['final_replay_result']['rtk']['params']['lam']);x=float(s2b['background_audit']['x_large_branch_reconstructed']);ss=math.hypot(1.0,math.sqrt(lamD)*x);ca2=x/(ss*ss*(ss+x));tt=x/(ss+1);Q=1+x/ss;mu2=3*rk/(2*x*(1+tt));MK=math.sqrt(mu2)*Q*ss*math.sqrt(ss);kstar=aa*MK;w=pk/rk;k=float(t['domain']['k_Mpc_inv']);cs2=ca2/(1+(k/kstar)**2);fc=t['frozen_checks'];off=json.loads(Path(a.off_identity).read_text());checks={'branch_count':True,'off_identity':off.get('all_branches_identical') is True};maxcar=maxur=maxrhs=maxmet=0.0;approx=onset=finpost=fincon=True;widths={};drift={};records=[]
 smap={'phi':'phi_CLASS_equals_Psi_N','delta_b':'delta_b','theta_b':'theta_b','delta_g':'delta_g','theta_g':'theta_g','delta_ur':'delta_ur','theta_ur':'theta_ur','shear_ur':'shear_ur','delta_khr_N':'delta_cdm_khr','theta_khr_N':'theta_cdm_khr'}
 for br in t['domain']['branches']:
  bid=br['id'];exp=build(bid);rows=parse(Path(a.observer_dir)/f'{bid}.csv');B=[r for r in rows if r['phase']=='BEFORE'];A=[r for r in rows if r['phase']=='AFTER'];checks['branch_count'] &= len(B)==len(A)==1; q=B[0];z=A[0];c=exp['carrier'];U=exp['ur_l_ge_3'];maxcar=max(maxcar,*(rel(q[n],c[m]) for n,m in smap.items()));maxur=max(maxur,*(rel(q['Fl'][l],U[l]) for l in range(3,18)))
  core=current_state_metric_core(k=k,a=aa,H=H,rb=rb,rg=rg,ru=ru,rk=rk,pk=pk,lam=float(t['domain']['lambda_HL']),Mc=float(t['domain']['M_c_Mpc_inv']),PsiN=c['phi_CLASS_equals_Psi_N'],db=c['delta_b'],tb=c['theta_b'],dg=c['delta_g'],tg=c['theta_g'],du=c['delta_ur'],tu=c['theta_ur'],dkN=c['delta_cdm_khr'],tkN=c['theta_cdm_khr']);tr=current_state_traceless_tca(k=k,a=aa,H=H,rb=rb,rg=rg,ru=ru,cb2=cb2,tau_c=tau,dtau_c=dtau,PsiN=core['Psi_N'],delta_b=c['delta_b'],theta_b=c['theta_b'],delta_g=c['delta_g'],theta_g=c['theta_g'],sigma_ur=c['shear_ur']);dyn=dynamic_derivative_slip(k=k,a=aa,H=H,Hprime=Hp,rb=rb,rg=rg,ru=ru,rk=rk,pk=pk,lam=float(t['domain']['lambda_HL']),Mc=float(t['domain']['M_c_Mpc_inv']),cb2=cb2,tau=tau,dtau=dtau,PsiN=c['phi_CLASS_equals_Psi_N'],db=c['delta_b'],tb=c['theta_b'],dg=c['delta_g'],tg=c['theta_g'],du=c['delta_ur'],tu=c['theta_ur'],sigma_ur=c['shear_ur'],dkN=c['delta_cdm_khr'],thetaN=c['theta_cdm_khr'],w=w,ca2=ca2,cs2=cs2)
  refs={'phi_prime':dyn['Psi_N_prime'],'theta_b_prime':dyn['theta_b_prime'],'theta_g_prime':dyn['theta_g_prime'],'theta_ur_prime':dyn['theta_ur_prime'],'delta_khr_N_prime':dyn['delta_khr_N_prime'],'theta_khr_N_prime':dyn['theta_khr_N_prime'],'tca_slip':dyn['tca_slip']};maxrhs=max(maxrhs,*(rel(q[n],v) for n,v in refs.items()),rel(q['Phi_N']*k*k,dyn['metric_euler']));maxmet=max(maxmet,rel(q['B'],core['B']),rel(q['Psi_N'],core['Psi_N']),rel(q['Phi_N'],tr['Phi_N']));approx &= q['tca']==z['tca']==0 and q['rsa']==z['rsa']==0 and q['ufa']==z['ufa']==0 and q['lmax']==z['lmax']==17;onset &= rel(q['a'],t['domain']['a_on'])<=float(fc['onset_relative_tolerance']);widths[bid]=z['tau']-q['tau'];finpost &= all(finite(z[n]) for n in smap) and all(finite(v) for v in z['Fl'].values());fincon &= all(finite(x[n]) for x in (q,z) for n in ['A_raw','A_norm','H_raw','H_norm','M_raw','M_norm','T_raw','T_norm']);drift[bid]={m:{'before':q[m+'_norm'],'after':z[m+'_norm'],'absolute_change':abs(z[m+'_norm']-q[m+'_norm'])} for m in ['A','H','M','T']};records.append({'branch':bid,'eta':[br['eta_D'],br['eta_C'],br['eta_S']],'step_width_Mpc':widths[bid],'constraint_drift_measurement_only':drift[bid]})
 pt=Path(a.patch).read_text();static='tol_perturb_integration' not in pt and 'dy[' not in pt and 'pvecmetric' not in pt;fixed=all(x in pt for x in ['branch=sys.argv[2]','S[1]']);noleg=all(x not in pt for x in ['deltaU_nlde','deltaV_nlde','deltaZ_nlde']);nodouble='khr_class_sources_newtonian' not in pt
 checks.update({'boundary_carrier':maxcar<=float(fc['boundary_carrier_relative_tolerance_vs_branch_builder']),'boundary_higher_ur':maxur<=float(fc['boundary_higher_ur_relative_tolerance_vs_s5b_control']),'first_rhs':maxrhs<=float(fc['first_rhs_relative_tolerance_vs_independent_current_state_kernel']),'kernel_metric':maxmet<=float(fc['kernel_metric_relative_tolerance_vs_independent_current_state_kernel']),'onset':onset,'approximation':approx,'rhs_calls':all(parse(Path(a.observer_dir)/f"{br['id']}.csv")[0]['rhs_calls']==int(t['execution']['before_rhs_calls']) and parse(Path(a.observer_dir)/f"{br['id']}.csv")[-1]['rhs_calls']==int(t['execution']['after_rhs_calls']) for br in t['domain']['branches']),'step_width':all(abs(v-float(t['execution']['retry_width_Mpc']))<=float(fc['step_width_absolute_tolerance_Mpc']) for v in widths.values()),'post_step_finite':finpost,'constraint_capture_finite':fincon,'same_kernel_integrator_tolerance_static_guard':static,'fixed_branch_selection_static_guard':fixed,'no_legacy_nlde_physical_role':noleg,'no_double_gauge_transform':nodouble,'higher_ur_status_remains_historical_control':all(x['status'].startswith('HIGHER_ORDER_HISTORICAL_CONTROL') for x in s5b['record']['ur_l_ge_3']),'s5c_envelope_not_interpreted_as_probability':True,'s2e_failed_parent_preserved':True,'threshold_changed':False});passed=all(v for n,v in checks.items() if n!='threshold_changed') and checks['threshold_changed'] is False;out={'schema':'RTK_C10_65S5D_NEXT_K_MULTIBRANCH_ONE_STEP_PRODUCTION_CANARY_RESULT_v1','gate':'C10.65s5d','classification':t['pass_classification'] if passed else t['fail_classification'],'checks':checks,'max_boundary_carrier_relative':maxcar,'max_boundary_higher_ur_relative':maxur,'max_first_rhs_relative':maxrhs,'max_kernel_metric_relative':maxmet,'records':records,'constraint_drift_measurement_only':drift,'threshold_changed':False,'interpretation':t['interpretation_if_pass'] if passed else 'At least one frozen multibranch production-entry check failed; diagnose without branch retuning or threshold relaxation.','next_gate':t['next_if_pass'] if passed else 'Diagnose C10.65s5d while preserving the frozen branch set and criteria.','non_claims':t['non_claims']};Path(a.output).write_text(json.dumps(out,indent=2,sort_keys=True,allow_nan=False)+'\n');print(out['classification']);print(json.dumps({'checks':checks,'maxrhs':maxrhs,'maxmetric':maxmet},sort_keys=True));return 0 if passed else 2
if __name__=='__main__':raise SystemExit(main())
