#!/usr/bin/env python3
import json, pathlib, datetime

ROOT=pathlib.Path(__file__).resolve().parents[2]
TARGET=ROOT/'research/theory_targets/RTK_C9_HMT_LAMBDA1_S3_ELL1_GAUGE_CLASSIFICATION_TARGET_v1.json'
RESULT=ROOT/'research/theory_results/RTK_C9_HMT_LAMBDA1_S3_ELL1_GAUGE_CLASSIFICATION_RESULT_v1.json'
CHECKPOINT=ROOT/'research/checkpoints/RTK_C9_HMT_LAMBDA1_S3_ELL1_GAUGE_CLASSIFICATION_2026-08-28.md'
PROV=ROOT/'research/provenance/RTK_C9_HMT_LAMBDA1_S3_ELL1_GAUGE_CLASSIFICATION_PROVENANCE_v1.json'

t=json.loads(TARGET.read_text())
assert t['parent_head']=='6e53cc177555c1cf6311e84702637ea4ad5c0042'
assert t['frozen_background']['dimension']==3
assert t['frozen_background']['lambda']==1
assert t['frozen_semantics']['full_FS_determinant_computed'] is False
assert t['frozen_semantics']['full_HMT_one_loop_evaluable'] is False
assert t['frozen_semantics']['full_C9_closed'] is False
assert t['frozen_semantics']['threshold_changed'] is False
assert t['frozen_semantics']['no_DSIR'] is True

# Round S^3 exact l=1 identities. Use a as a symbolic scale and track only coefficients.
# For any l=1 scalar harmonic f (restriction of an ambient linear coordinate),
# nabla_i nabla_j f = -(1/a^2) g_ij f and -nabla^2 f = 3/a^2 f.
hessian_coeff_times_a2=-1
laplacian_eigen_times_a2=3
trace_from_hessian=-3
assert trace_from_hessian == -laplacian_eigen_times_a2

# Choose xi_i=-(a^2/2) nabla_i f. Then
# L_xi g_ij = 2 nabla_(i xi_j) = -a^2 nabla_i nabla_j f = f g_ij.
xi_prefactor_times_a_minus2=-0.5
lie_metric_coeff = 2*xi_prefactor_times_a_minus2*hessian_coeff_times_a2
assert abs(lie_metric_coeff-1.0)<1e-12

# Parent second-class block C12=(R/3)(-R-2 nabla^2), R=6/a^2.
R_times_a2=6
c12_inner_times_a2=-R_times_a2 + 2*laplacian_eigen_times_a2
assert c12_inner_times_a2==0

# Scalar harmonic degeneracy on S^3 is (l+1)^2.
ell=1
scalar_ell1_dimension=(ell+1)**2
assert scalar_ell1_dimension==4

classification='RTK_C9_HMT_LAMBDA1_S3_ELL1_ZERO_MODES_SPATIAL_DIFF_GAUGE_PASS_SCOPED'
result={
  'classification':classification,
  'frozen_target_parent_head':t['parent_head'],
  'target_frozen_commit':'620982d5793c05f8da6095b5db21f9e399d9795a',
  'exact_identities':{
    'ell1_hessian':'nabla_i nabla_j f = -(1/a^2) g_ij f',
    'ell1_laplacian':'-nabla^2 f = 3/a^2 f',
    'chosen_spatial_diff_covector':'xi_i = -(a^2/2) nabla_i f',
    'metric_lie_derivative':'2 nabla_(i xi_j) = f g_ij',
    'parent_C12_on_ell1':'(R/3)(-R-2 nabla^2) f = 0 for R=6/a^2',
    'scalar_ell1_dimension':scalar_ell1_dimension
  },
  'findings':{
    'every_scalar_ell1_conformal_zero_mode_in_frozen_block_is_tangent_to_spatial_diffeomorphism_orbit':True,
    'ell1_zero_modes_are_gauge_in_this_frozen_scalar_conformal_sector':True,
    'ell1_zero_modes_demonstrate_physical_second_class_rank_loss':False,
    'ell0_parent_nonzero_rank_preserved':True,
    'ell_ge2_parent_nonzero_rank_preserved':True,
    'full_HMT_gauge_fixed_constraint_matrix_constructed':False,
    'complete_zero_mode_quotient_constructed':False,
    'full_FS_determinant_computed':False,
    'full_HMT_one_loop_evaluable':False,
    'full_C9_closed':False,
    'soft_s_retest_allowed':False,
    'production_k003_unblocked':False,
    'threshold_changed':False,
    'no_DSIR':True
  },
  'interpretation':'On the frozen round-S3 lambda=1 background, the four scalar ell=1 conformal perturbations that annihilate the previously derived C12 block are exactly metric Lie derivatives generated by gradients of ell=1 harmonics. Therefore this residual kernel is a spatial-diffeomorphism gauge kernel in this scoped scalar/conformal block, not evidence for a physical loss of the second-class rank. This does not yet construct the complete HMT gauge-fixed Faddeev-Senjanovic determinant.',
  'next_gate':'Construct the reduced scalar/conformal determinant on round S3 with the ell=1 spatial-diffeomorphism gauge sector explicitly projected out, while keeping the remaining HMT constraint/gauge sectors open; then test positivity/nonzero spectrum of the reduced C12 block and document zero-mode quotient normalization separately.'
}
RESULT.parent.mkdir(parents=True,exist_ok=True); RESULT.write_text(json.dumps(result,indent=2)+'\n')
CHECKPOINT.parent.mkdir(parents=True,exist_ok=True); CHECKPOINT.write_text(f'''# RTK C9 HMT lambda=1 S3 ell=1 gauge-classification checkpoint

Classification: `{classification}`

Frozen target commit: `620982d5793c05f8da6095b5db21f9e399d9795a`.

For every scalar ell=1 harmonic f on round S3,

nabla_i nabla_j f = -(1/a^2) g_ij f.

Choosing xi_i=-(a^2/2)nabla_i f gives

2 nabla_(i xi_j) = f g_ij,

so the conformal metric perturbation that lies in the ell=1 kernel of C12 is exactly a spatial-diffeomorphism gauge direction. The scalar ell=1 space has dimension four. Thus the residual ell=1 kernel found in the parent constant-curvature witness is gauge in this frozen scalar/conformal sector, not evidence for physical second-class rank loss.

Strict scope: the complete HMT gauge-fixed constraint matrix and full zero-mode quotient have not been constructed. Full FS determinant OPEN; full HMT one-loop BLOCKED; full C9 OPEN; soft-s retest forbidden; k=0.03 production blocked; thresholds unchanged.

Next gate: construct the reduced scalar/conformal C12 determinant/spectrum with ell=1 gauge modes explicitly projected out, without claiming a full HMT determinant.
''')
PROV.parent.mkdir(parents=True,exist_ok=True); PROV.write_text(json.dumps({
  'created_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
  'target':str(TARGET.relative_to(ROOT)),
  'script':str(pathlib.Path(__file__).relative_to(ROOT)),
  'result':str(RESULT.relative_to(ROOT)),
  'checkpoint':str(CHECKPOINT.relative_to(ROOT)),
  'method':'exact round-S3 ell=1 Hessian identity plus explicit spatial-diffeomorphism Lie-derivative construction and parent C12 spectral substitution',
  'external_crosscheck':'standard S3 scalar/tensor harmonic geometry; no external numerical fit',
  'no_DSIR':True,
  'no_threshold_change':True
},indent=2)+'\n')
print(json.dumps(result,indent=2))
