#!/usr/bin/env python3
"""Global envelope of the finite-Mc O(4) resolvent metric-variation kernel.

For d=3 and output k=p+q, write m=M_c/k>0, x=q/k>0.  The exact
conformal-metric variation kernel from the companion theorem is
 K_a/gamma = -m^2[3x^2-x cos(theta)]/[(m^2+1)(m^2+x^2)].
The worst angular magnitude is bounded by
 E(m,x)=m^2(3x^2+x)/[(m^2+1)(m^2+x^2)].
This gate proves E<3 globally and identifies the exact stationary x at fixed m.
"""
import json
import sympy as sp
m,x=sp.symbols('m x', positive=True, finite=True)
E=sp.factor(m**2*(3*x**2+x)/((m**2+1)*(m**2+x**2)))
# Direct global proof E<3: denominator times (3-E) is a positive quadratic.
pos=sp.expand(3*(m**2+1)*(m**2+x**2)-m**2*(3*x**2+x))
assert sp.expand(pos-(3*m**4+3*m**2+3*x**2-m**2*x))==0
# Complete square in x.
completed=3*(x-m**2/sp.Integer(6))**2 + sp.Rational(35,12)*m**4 + 3*m**2
assert sp.simplify(pos-completed)==0

# Unique positive fixed-m stationary point.
dE=sp.factor(sp.diff(E,x))
xstar=3*m**2+m*sp.sqrt(9*m**2+1)
assert sp.simplify((xstar**2-6*m**2*xstar-m**2))==0
# derivative numerator changes from + at x=0 to - after xstar, so this is max.
num=sp.factor(sp.together(dE).as_numer_denom()[0])
assert num==m**2*(6*m**2*x+m**2-x**2)
Emax=sp.factor(E.subs(x,xstar))
# asymptotic limits.
assert sp.limit(Emax,m,0,dir='+')==0
assert sp.limit(Emax,m,sp.oo)==3

out={
 'classification':'RTK_C9_PROJECTABLE_U1_FINITE_MC_O4_KERNEL_ENVELOPE_PASS',
 'status_scope':'GREEN_GLOBAL_RESOLVENT_O4_KERNEL_BOUND_COMPLETE_FULL_O4_OBSERVABLE_PENDING',
 'domain':'d=3, M_c>0, k>0, q>0, conformal O(2) spatial metric perturbation, exact auxiliary resolvent',
 'dimensionless_envelope':'E=m^2(3x^2+x)/[(m^2+1)(m^2+x^2)], m=M_c/k, x=q/k',
 'global_bound':'0<=|K_a|/|gamma| <= E(m,x) < 3',
 'positive_remainder_proof':'3(m^2+1)(m^2+x^2)-m^2(3x^2+x)=3(x-m^2/6)^2+(35/12)m^4+3m^2>0',
 'fixed_m_maximum':'x_star=3m^2+m sqrt(9m^2+1)',
 'limits':['E_max->0 as M_c/k->0','E_max->3 from below as M_c/k->infinity'],
 'interpretation':'Finite-Mc O4 mode mixing is genuine but the isolated resolvent metric-variation kernel is uniformly bounded; no UV/IR pole is generated by this kernel itself.',
 'non_claims':['does not bound the sum of all O4 terms','does not produce beta or alpha2 for a concrete experiment','does not include nonlinear self-gravity beyond the stated conformal variation'],
 'next_gate':'use this uniform bound to control truncation/error in the heavy source-specific O4 convolution audit and combine with filtered J_A plus ordinary stress terms.'
}
open('c9_projectable_u1_finite_mc_o4_kernel_envelope_result.json','w').write(json.dumps(out,indent=2,sort_keys=True)+'\n')
print(out['classification'],json.dumps(out,sort_keys=True))
