#!/usr/bin/env python3
"""C9 radiative tuning-only obstruction for the nonprojectable U(1) completion.

Primary literature input: Mukohyama, Namba, Saitou, Watanabe,
arXiv:1504.07357 / Phys. Rev. D 92, 024005 (2015).

Published nonlinear Hamiltonian theorem:
- the scalar graviton is absent iff eta1=eta2=0;
- eta1 a_i a^i sigma and eta2 D_i a^i sigma are marginal for any z,d;
- they are expected to be generated by quantum corrections;
- eta2 != 0 gives the scalar already in linear perturbations about Minkowski;
- eta2=0 with eta1 !=0 can hide it at linear order because a_i a^i sigma is
  cubic about flat homogeneous lapse, but the nonlinear Hamiltonian DOF remains.

This executable gate does not calculate beta functions.  It classifies whether
"make radiative eta1,eta2 merely very small" can preserve the exact classical
3-DOF claim of the current RTK completion.  Since DOF count changes for every
nonzero eta1 or eta2, the answer is no.  The derivative operators also do not
supply an algebraic mass gap by themselves, so smallness alone is not a
certificate that the new scalar lies above the EFT cutoff.
"""
import json
import sympy as sp

eta1,eta2,eps=sp.symbols('eta1 eta2 eps', real=True, finite=True)
# Exact special surface: codimension two in the allowed marginal-coupling plane.
exact_surface=sp.And(sp.Eq(eta1,0),sp.Eq(eta2,0))
assert exact_surface != sp.And(sp.Abs(eta1)<eps, sp.Abs(eta2)<eps)

# Flat-background perturbative order bookkeeping.
# a_i~O(delta), sigma~O(delta): eta2 D.a sigma starts O(delta^2),
# eta1 a^2 sigma starts O(delta^3).  Neither is O(delta^0 sigma^2), i.e. a mass.
order_eta2=2
order_eta1=3
assert order_eta2==2 and order_eta1==3

out={
  'classification':'RTK_C9_U1_RADIATIVE_TUNING_ONLY_NOGO_PASS',
  'status_scope':'BLACK_TUNING_ONLY_AS_EXACT_3DOF_PROTECTION_OTHER_C9_MECHANISMS_OPEN',
  'primary_source':'Mukohyama-Namba-Saitou-Watanabe arXiv:1504.07357, action Eq.(20), scaling Eq.(19), Sec.IV/V nonlinear DOF discussion',
  'published_exact_dof_surface':'eta1=eta2=0 iff no scalar graviton in the nonprojectable U(1) gravity sector',
  'codimension':'2',
  'radiative_fact':'both allowed operators are marginal and are expected by the source paper to be generated by quantum corrections',
  'linear_nonlinear_bifurcation':{
    'eta2_nonzero':'generic scalar graviton is already present at linear order around Minkowski',
    'eta2_zero_eta1_nonzero':'linear flat-background analysis can miss the scalar because a_i a^i sigma starts at cubic perturbative order, but the nonlinear Hamiltonian DOF is present'
  },
  'perturbative_orders_flat':{
    'eta2_Da_sigma':'quadratic O(delta^2)',
    'eta1_a2_sigma':'cubic O(delta^3)'
  },
  'mass_gap_statement':'These counterterms are derivative/marginal operators; coefficient smallness alone does not provide an algebraic scalar mass term or a proof that the extra DOF is above the EFT cutoff.',
  'exact_tuning_conclusion':'For an exact 3-DOF completion, any nonzero radiative eta1 or eta2 leaves the special constraint surface. An inequality |eta_i|<epsilon is therefore not a substitute for eta1=eta2=0.',
  'c9_consequence':'The tuning-only option is insufficient as protection of the exact 3-DOF claim. Viability now requires an exact Ward/symmetry protection, an RG-invariant zero surface, or a new structural/degenerate constraint mechanism that survives the allowed counterterms.',
  'non_claims':[
    'does not compute the one-loop beta functions of the completed RTK action',
    'does not prove no enlarged symmetry can forbid eta1 and eta2',
    'does not prove every small nonzero eta_i is observationally excluded',
    'does not calculate a strong-coupling scale for the nonlinear eta1-only scalar',
    'does not exclude replacing the current nonprojectable U1 carrier by another constraint architecture'
  ],
  'next_gate':'search for an additional exact symmetry/Ward identity compatible with the frozen RTK mixed operator and elliptic matter compensator; independently test whether an alternative auxiliary constraint can keep rank after eta1,eta2 counterterms are admitted.'
}
open('c9_u1_radiative_tuning_only_nogo_result.json','w').write(json.dumps(out,indent=2,sort_keys=True)+'\n')
print(out['classification'],json.dumps(out,sort_keys=True))
