#!/usr/bin/env python3
"""Stage 4A pilot nested sampling for RTK/LCDM.

This runner intentionally uses the already validated Planck+Pantheon+BOSS
likelihood core. It is a bounded pilot inference run, not a production
cosmological posterior. The primary nested run uses the effective-growth BOSS
mapping. The k=0.1 h/Mpc mapping is evaluated for every stored sample and
importance-reweighted from the primary posterior; the reweighting ESS is
reported so that poor overlap is visible rather than hidden.
"""
from pathlib import Path
import csv, json, math, os, sys
import numpy as np
from dynesty import NestedSampler

# inference_core.py is generated by CI from the tested joint_profile_runner.py
# before its coordinate-search block, with the corrected CLASS primordial names
# A_s and n_s.
import inference_core as L

MODEL=(sys.argv[2] if len(sys.argv)>2 else os.environ.get('RTK_MODEL','RTK')).upper()
PRIMARY=(sys.argv[3] if len(sys.argv)>3 else os.environ.get('RTK_RSD_MAPPING','eff')).lower()
if MODEL not in ('RTK','LCDM'):
    raise SystemExit('model must be RTK or LCDM')
if PRIMARY not in ('eff','k01'):
    raise SystemExit('mapping must be eff or k01')

NLIVE=int(os.environ.get('RTK_NLIVE','24'))
MAXCALL=int(os.environ.get('RTK_MAXCALL','260'))
DLOGZ=float(os.environ.get('RTK_DLOGZ','5.0'))
SEED=int(os.environ.get('RTK_SEED','20260815')) + (0 if MODEL=='LCDM' else 17)
OUT=Path('output/nested')/MODEL.lower(); OUT.mkdir(parents=True,exist_ok=True)

# Pilot prior box. Evidence values are conditional on these explicit bounds.
# lambda_D is log-uniform because the physically interesting scale spans orders
# of magnitude; the other parameters are uniform in the listed coordinates.
COMMON=[
    ('h',   0.655, 0.705, 'linear'),
    ('Ob',  0.044, 0.052, 'linear'),
    ('Om',  0.235, 0.285, 'linear'),
    ('As',  1.90e-9, 2.25e-9, 'linear'),
    ('ns',  0.945, 0.985, 'linear'),
    ('zre', 4.5,   9.5,   'linear'),
]
PARAMS=([('lam',300.0,30000.0,'log')] if MODEL=='RTK' else []) + COMMON
NDIM=len(PARAMS)


def prior_transform(u):
    x=[]
    for ui,(name,lo,hi,kind) in zip(u,PARAMS):
        if kind=='log':
            x.append(math.exp(math.log(lo)+float(ui)*(math.log(hi)-math.log(lo))))
        else:
            x.append(lo+float(ui)*(hi-lo))
    return np.asarray(x,dtype=float)


def theta_to_params(theta):
    p={'lam':0.0}
    for v,(name,lo,hi,kind) in zip(theta,PARAMS): p[name]=float(v)
    return p


def cleanup_tag(tag):
    # The likelihood result itself is cached in memory, so the many CLASS output
    # files can be removed immediately after each expensive call.
    for p in L.OUT.glob(tag+'_*'):
        try: p.unlink()
        except OSError: pass
    for p in (Path(f'profile_{tag}.ini'),Path(f'profile_{tag}.log')):
        try: p.unlink()
        except OSError: pass


def score_of(r,mapping):
    return r['score'] if mapping=='eff' else r['score_k01']


def loglike(theta):
    p=theta_to_params(theta)
    r=L.evaluate(MODEL,p)
    if not r.get('ok'):
        if r.get('tag'): cleanup_tag(r['tag'])
        return -1.0e300
    val=-0.5*float(score_of(r,PRIMARY))
    cleanup_tag(r['tag'])
    return val if math.isfinite(val) else -1.0e300


def logsumexp(a):
    a=np.asarray(a,dtype=float); m=np.max(a)
    if not np.isfinite(m): return m
    return float(m+np.log(np.sum(np.exp(a-m))))


def weighted_quantile(x,w,qs=(0.16,0.5,0.84)):
    x=np.asarray(x); w=np.asarray(w); idx=np.argsort(x); x=x[idx]; w=w[idx]
    c=np.cumsum(w); c/=c[-1]
    return [float(np.interp(q,c,x)) for q in qs]

print('NESTED_PILOT_CONFIG',json.dumps({
    'model':MODEL,'primary_mapping':PRIMARY,'nlive':NLIVE,'maxcall':MAXCALL,
    'dlogz':DLOGZ,'seed':SEED,'priors':PARAMS
},sort_keys=True),flush=True)

rng=np.random.default_rng(SEED)
sampler=NestedSampler(loglike,prior_transform,NDIM,nlive=NLIVE,
                      bound='multi',sample='rwalk',rstate=rng)
checkpoint=str(OUT/'checkpoint.pkl')
sampler.run_nested(maxcall=MAXCALL,dlogz=DLOGZ,print_progress=True,
                   checkpoint_file=checkpoint,checkpoint_every=120)
res=sampler.results
samples=np.asarray(res.samples,dtype=float)
logl_primary=np.asarray(res.logl,dtype=float)
logz=float(res.logz[-1]); logzerr=float(res.logzerr[-1])
logw=np.asarray(res.logwt,dtype=float)-logz
logw-=logsumexp(logw)
w=np.exp(logw); w/=w.sum()

# Evaluate the alternate RSD mapping for all nested samples. These should be
# cache hits for points already visited by dynesty, so no new CLASS calculation
# is normally required.
alt='k01' if PRIMARY=='eff' else 'eff'
logl_alt=[]
for th in samples:
    r=L.evaluate(MODEL,theta_to_params(th))
    logl_alt.append(-0.5*float(score_of(r,alt)) if r.get('ok') else -1e300)
logl_alt=np.asarray(logl_alt)
delta=logl_alt-logl_primary
log_ratio=logsumexp(logw+delta)
logz_alt=logz+log_ratio
logw_alt=logw+delta-log_ratio
w_alt=np.exp(logw_alt); w_alt/=w_alt.sum()
ess_primary=float(1.0/np.sum(w*w))
ess_alt=float(1.0/np.sum(w_alt*w_alt))

imax=int(np.argmax(logl_primary)); best_theta=samples[imax]
best=L.evaluate(MODEL,theta_to_params(best_theta))

summary={
 'model':MODEL,'primary_mapping':PRIMARY,'alternate_mapping':alt,
 'nlive':NLIVE,'maxcall_budget':MAXCALL,'dlogz_target':DLOGZ,'seed':SEED,
 'niter':int(res.niter),'ncall':int(np.sum(res.ncall)),
 'budget_limited':bool(np.sum(res.ncall)>=MAXCALL),
 'logZ_primary':logz,'logZerr_primary':logzerr,
 'logZ_alt_importance':float(logz_alt),
 'ess_primary':ess_primary,'ess_alt_reweighted':ess_alt,
 'best_logL_primary':float(logl_primary[imax]),
 'best_params':theta_to_params(best_theta),
 'best_components':{k:best.get(k) for k in (
     'rd','logL_lowT','logL_lowE','logL_high','logL_planck',
     'chi2_SN','chi2_BOSS_eff','chi2_BOSS_k01','score','score_k01')},
 'priors':[{'name':n,'lo':lo,'hi':hi,'kind':kind} for n,lo,hi,kind in PARAMS],
 'posterior_primary':{},'posterior_alt_reweighted':{}
}
for j,(name,lo,hi,kind) in enumerate(PARAMS):
    q=weighted_quantile(samples[:,j],w); qa=weighted_quantile(samples[:,j],w_alt)
    summary['posterior_primary'][name]={'q16':q[0],'q50':q[1],'q84':q[2]}
    summary['posterior_alt_reweighted'][name]={'q16':qa[0],'q50':qa[1],'q84':qa[2]}

(OUT/'summary.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n')
with (OUT/'samples.csv').open('w',newline='') as f:
    fields=[p[0] for p in PARAMS]+['logL_primary','logL_alt','weight_primary','weight_alt']
    cw=csv.DictWriter(f,fieldnames=fields); cw.writeheader()
    for i,th in enumerate(samples):
        row={name:float(v) for v,(name,_,_,_) in zip(th,PARAMS)}
        row.update(logL_primary=float(logl_primary[i]),logL_alt=float(logl_alt[i]),
                   weight_primary=float(w[i]),weight_alt=float(w_alt[i]))
        cw.writerow(row)

# Keep the raw expensive-evaluation history for diagnostics and reproducibility.
if L.HISTORY:
    fields=sorted(set().union(*(r.keys() for r in L.HISTORY)))
    with (OUT/'likelihood_history.csv').open('w',newline='') as f:
        cw=csv.DictWriter(f,fieldnames=fields);cw.writeheader();cw.writerows(L.HISTORY)

print('NESTED_PILOT_RESULT',json.dumps(summary,sort_keys=True),flush=True)
print('NESTED_PILOT_PASS',flush=True)
