#!/usr/bin/env python3
"""Constructive local quadratic-EFT audit for the implemented RTK scalar dispersion.

This establishes an *existence result at quadratic/linear level*, not a unique
fundamental action, nonlinear completion, loop-level proof, or UV completion.

For a physical Fourier momentum q, consider the preferred-frame local quadratic
Lagrangian density

  L2(q) = 1/2 K [1 + q^2/M^2] |pi_dot|^2 - 1/2 G q^2 |pi|^2,

which in position space is generated by

  K/2 (pi_dot)^2 + K/(2 M^2) (grad pi_dot)^2 - G/2 (grad pi)^2.

It contains higher *spatial* derivatives but no higher time derivative.  Its
linear dispersion is

  omega^2 = (G/K) q^2 / [1 + q^2/M^2].

Taking G=rho+p, K=(rho+p)/c_a^2 and M=k_* exactly reproduces the implemented
c_s^2(q)=c_a^2/[1+(q/k_*)^2].  If G,K,M^2>0, the canonical Hamiltonian of every
Fourier mode is positive.

We also prove symbolically that the coded background c_a^2 equals dp/drho,
eliminating the floating-point cancellation that affected the earlier proxy
check at extreme scales.
"""
import json, math
import sympy as sp

# Exact symbolic background identity.
x, lam = sp.symbols('x lam', positive=True, finite=True)
s = sp.sqrt(1 + lam*x**2)
rho = x*(1 + x/(s+1))
p = (x/s)*(x/(s+1))
ca2 = (x/s)/(s*(s+x))
dpdrho = sp.simplify(sp.diff(p,x)/sp.diff(rho,x))
identity = sp.simplify(dpdrho-ca2)

# Symbolic quadratic action / Hamiltonian checks.
K,G,M2,q2 = sp.symbols('K G M2 q2', positive=True, finite=True)
A = sp.simplify(K*(1+q2/M2))
omega2 = sp.simplify(G*q2/A)
P = sp.symbols('P', real=True)
pi = sp.symbols('pi', real=True)
H = sp.simplify(P**2/(2*A) + G*q2*pi**2/2)

# Broad numerical sign audit over the implemented background formulas.
LAMBDAS=[1e-12,1e-8,1e-4,1.0,1e4,1e8,1e12]
XS=[10.0**(j/2) for j in range(-24,25)]
KRS=[0.0,1e-8,1e-4,1e-2,0.1,1.0,10.0,1e2,1e4,1e8]
viol=[]
minG=math.inf; minK=math.inf; minA=math.inf; minw=math.inf
points=0
for la in LAMBDAS:
    for xx in XS:
        ss=math.hypot(1.0,math.sqrt(la)*xx)
        rr=xx/ss; tt=xx/(ss+1.0)
        rh=xx*(1.0+tt); pr=rr*tt
        c=rr/(ss*(ss+xx))
        g=rh+pr; k=g/c
        minG=min(minG,g); minK=min(minK,k)
        if not all(map(math.isfinite,(rh,pr,c,g,k))) or not (rh>0 and c>0 and g>0 and k>0):
            viol.append({'kind':'background_sign','lambda_D':la,'x':xx,'rho':rh,'p':pr,'ca2':c,'G':g,'K':k})
        for kr in KRS:
            aa=k*(1.0+kr*kr)
            w2=(g/k)*(kr*kr)/(1.0+kr*kr) if kr>0 else 0.0
            points+=1
            minA=min(minA,aa); minw=min(minw,w2)
            if not (math.isfinite(aa) and aa>0 and math.isfinite(w2) and w2>=0):
                viol.append({'kind':'mode_sign','lambda_D':la,'x':xx,'k_over_kstar':kr,'A':aa,'omega2_over_kstar2':w2})

ok = (identity==0 and not viol)
out={
 'status':'PASS' if ok else 'FAIL',
 'classification':'CONSTRUCTIVE_LOCAL_QUADRATIC_EFT_EXISTENCE_AT_LINEAR_LEVEL',
 'symbolic':{
   'background_ca2_equals_dpdrho': bool(identity==0),
   'kinetic_fourier_coefficient':'K*(1+q^2/M^2)',
   'dispersion':'omega^2=(G/K)*q^2/(1+q^2/M^2)',
   'hamiltonian':'P^2/[2*K*(1+q^2/M^2)] + G*q^2*pi^2/2',
   'no_higher_time_derivatives_in_candidate': True,
 },
 'mapping_to_implemented_sector':{
   'G':'rho+p', 'K':'(rho+p)/ca2', 'M':'k_star',
   'implemented_dispersion_reproduced_exactly': True,
 },
 'grid':{'points':points,'violations':viol[:20],
         'min_G':minG,'min_K':minK,'min_mode_kinetic_coefficient':minA,'min_omega2_over_kstar2':minw},
 'interpretation':{
   'quadratic_linear_local_action_exists':'PROVED_FOR_THIS_PREFERRED_FRAME_RECONSTRUCTION',
   'positive_quadratic_hamiltonian':'PROVED_IF_G_K_M2_POSITIVE_AND_GRID_CHECKED_FOR_IMPLEMENTED_G_K',
   'fundamental_action_uniqueness':'NOT_CLAIMED',
   'nonlinear_constraint_algebra':'NOT_YET_DERIVED',
   'strong_coupling_scale':'NOT_YET_DERIVED',
   'one_loop_radiative_stability':'NOT_YET_DERIVED',
   'uv_completion':'NOT_CLAIMED',
   'next_required_step':'DERIVE_STRONG_COUPLING_AND_NONLINEAR_CONSTRAINT_STRUCTURE'
 }
}
print(json.dumps(out,indent=2,sort_keys=True))
if not ok: raise SystemExit(2)
