#!/usr/bin/env python3
"""C8 U(1) classical-intersection gate.

This gate combines two published classical results only after matching their
action notation explicitly.

PPN action notation (arXiv:1310.6666):

  L_S = sigma [sigma1 a_i a^i + sigma2 D_i a^i + 2 Lambda_g - R]

with the U(1)-invariant sigma=(A-mathcal A)/N (up to the paper's prepotential
sign convention).  One displayed exact-GR PPN family is

  a1=kappa=1, sigma2=0.

Hamiltonian action notation (arXiv:1504.07357):

  (2 Omega - eta0 R + eta1 a_i a^i + eta2 D_i a^i) sigma.

After the conventional redundant normalization eta0=1 and Omega=Lambda_g,
coefficient matching of the same invariant operator basis gives

  eta1=sigma1, eta2=sigma2.

The Hamiltonian theorem states that the unwanted gravity scalar is absent at
the fully nonlinear classical level iff eta1=eta2=0.  Therefore the PPN
family-I surface contains a nonlinear gravity-scalar-free sub-surface
sigma1=sigma2=0.

The direct rolling RTK coefficient dictionary separately gives beta0=2.  Since
family-I does not fix beta0, the tuple

  a1=kappa=1, sigma1=sigma2=0, beta0=2, gamma1=-1

is algebraically compatible with all three *classical* requirements encoded
here: displayed GR-PPN family-I conditions, canonical IR curvature sign, and
the Hamiltonian no-unwanted-gravity-scalar surface.

This is NOT a viability theorem.  In particular arXiv:1504.07357 shows that the
eta1/eta2 operators are marginal and expected to be regenerated by quantum
corrections, so this special no-gravity-scalar surface is radiatively unstable
without an additional protection mechanism.
"""

import json
import sympy as sp

sigma1,sigma2,eta0,eta1,eta2 = sp.symbols('sigma1 sigma2 eta0 eta1 eta2', real=True)
a1,kappa,beta0,gamma1 = sp.symbols('a1 kappa beta0 gamma1', real=True)
Omega,Lambda_g = sp.symbols('Omega Lambda_g', real=True)

# Same invariant operator basis after eta0 normalization and background-constant match.
dictionary = {eta0:sp.Integer(1), Omega:Lambda_g, eta1:sigma1, eta2:sigma2}
assert eta1.subs(dictionary) == sigma1
assert eta2.subs(dictionary) == sigma2

# Displayed exact-GR PPN family I plus the Hamiltonian no-gravity-scalar subset.
candidate={
    a1:sp.Integer(1), kappa:sp.Integer(1), sigma1:sp.Integer(0),
    sigma2:sp.Integer(0), beta0:sp.Integer(2), gamma1:sp.Integer(-1)
}
assert (a1-1).subs(candidate) == 0
assert (kappa-1).subs(candidate) == 0
assert sigma2.subs(candidate) == 0
assert eta1.subs(dictionary).subs(candidate) == 0
assert eta2.subs(dictionary).subs(candidate) == 0
assert (beta0-2).subs(candidate) == 0
assert (gamma1+1).subs(candidate) == 0

out={
  'classification':'RTK_ROUTE_B_U1_CLASSICAL_PPN_DOF_INTERSECTION_OPEN',
  'action_dictionary':{
    'eta0':1,
    'Omega':'Lambda_g',
    'eta1':'sigma1',
    'eta2':'sigma2'
  },
  'displayed_GR_PPN_family_I':{'a1':1,'kappa':1,'sigma2':0},
  'Hamiltonian_no_unwanted_gravity_scalar_surface':{'eta1':0,'eta2':0,'equivalent_sigma1':0,'equivalent_sigma2':0},
  'direct_RTK_slice':{'beta0':2,'gamma1':-1},
  'classical_intersection_candidate':{'a1':1,'kappa':1,'sigma1':0,'sigma2':0,'beta0':2,'gamma1':-1},
  'interpretation':'The published classical GR-PPN family-I conditions, the fully nonlinear no-unwanted-gravity-scalar Hamiltonian surface, and the direct RTK beta0=2 coefficient slice have a nonempty algebraic intersection after matching action notation.',
  'radiative_warning':'The eta1/eta2 operators are marginal and expected to be generated by quantum corrections; eta1=eta2=0 is not technically natural in the generic nonprojectable U(1) theory.',
  'non_claims':[
    'not a proof of the coupled gravity+RTK scalar total DOF count',
    'not a proof that beta0=2 solves all static field equations for the selected matter frame',
    'not a Newton/Friedmann normalization calculation',
    'not a tensor/GW, compact-object or EFT-cutoff result',
    'not a radiatively stable UV completion'
  ],
  'next_step':'Use this exact classical candidate tuple as the frozen starting surface for the coupled RTK-scalar Hamiltonian/static equations, then test whether an additional symmetry/constraint can protect the eta1=eta2=0 surface radiatively.'
}
print('RTK_ROUTE_B_U1_CLASSICAL_PPN_DOF_INTERSECTION_OPEN',json.dumps(out,sort_keys=True))
