#!/usr/bin/env python3
"""C8 two-auxiliary positivity/cancellation gate.

Question
--------
Can two local dynamical auxiliary fields remove the extra frequency pole of a
single dynamical auxiliary by an exact determinant cancellation while keeping
an ordinary positive quadratic auxiliary block?

Let the auxiliary quadratic matrix at fixed spatial momentum be

  M(x) = M0 - x Z,   x=omega^2,

with real symmetric 2x2 matrices.  The denominator generated by integrating out
the auxiliaries contains

  det M(x) = D0 - D1 x + D2 x^2,

where

  D0 = det M0,
  D1 = tr(adj(M0) Z),
  D2 = det Z.

A rank-one kinetic matrix Z can set D2=0.  However, if M0 is positive definite
and Z is positive semidefinite and nonzero, adj(M0)=det(M0) M0^{-1} is positive
definite, so

  D1 = tr(adj(M0) Z) > 0.

Thus the determinant retains nontrivial omega^2 dependence and an auxiliary
frequency pole.  Exact removal of all frequency dependence therefore requires
Z=0 inside this positive class, or leaving the class through an indefinite/
gauge-degenerate structure that must be analyzed separately for DOF/ghosts.

This is intentionally scoped.  It is not a no-go for constrained gauge systems,
indefinite intermediate variables that are nondynamical after a full Dirac
analysis, higher-dimensional exact pole-zero cancellations, or retarded/nonlocal
completions.
"""

import json
import sympy as sp

x = sp.symbols('x', real=True)
a,c,d,u,v,w = sp.symbols('a c d u v w', finite=True, real=True)
M0 = sp.Matrix([[a,c],[c,d]])
Z = sp.Matrix([[u,v],[v,w]])

poly = sp.Poly(sp.expand((M0-x*Z).det()), x)
D2 = sp.factor(poly.coeff_monomial(x**2))
minus_D1 = sp.factor(poly.coeff_monomial(x))
D0 = sp.factor(poly.coeff_monomial(1))
D1 = sp.factor(-minus_D1)

assert D0 == a*d-c**2
assert D1 == a*w+d*u-2*c*v
assert D2 == u*w-v**2

# Exact trace identity D1=tr(adj(M0) Z).
adjM0 = sp.Matrix([[d,-c],[-c,a]])
trace_identity = sp.factor(sp.trace(adjM0*Z))
assert sp.simplify(trace_identity-D1) == 0

# Constructive positivity proof for rank-one PSD Z=z z^T.
z1,z2 = sp.symbols('z1 z2', real=True)
Zrank1 = sp.Matrix([[z1**2,z1*z2],[z1*z2,z2**2]])
D2_rank1 = sp.factor(Zrank1.det())
D1_rank1 = sp.factor(sp.trace(adjM0*Zrank1))
assert D2_rank1 == 0
# D1 = z^T adj(M0) z exactly.
z = sp.Matrix([z1,z2])
quad = sp.factor((z.T*adjM0*z)[0])
assert sp.simplify(D1_rank1-quad) == 0

# Sylvester positivity of M0: a>0 and det(M0)>0 implies adj(M0)>0 as well
# (its leading minor d=(det+c^2)/a >0 and det(adjM0)=det(M0)>0).
Delta = sp.symbols('Delta', positive=True, finite=True, real=True)
ap = sp.symbols('ap', positive=True, finite=True, real=True)
cp = sp.symbols('cp', finite=True, real=True)
d_from_pd = sp.simplify((Delta+cp**2)/ap)
adj11 = d_from_pd
adj_det = sp.simplify(d_from_pd*ap-cp**2)
assert sp.simplify(adj_det-Delta) == 0
assert adj11.is_positive

out = {
  'classification':'RTK_ROUTE_B_TWO_AUXILIARY_POSITIVE_CANCELLATION_GATE_PASS',
  'determinant':{
    'form':'det(M0-omega^2 Z)=D0-D1 omega^2+D2 omega^4',
    'D0':'det(M0)',
    'D1':'tr(adj(M0) Z)',
    'D2':'det(Z)'
  },
  'rank_one_Z':'det(Z)=0 removes the omega^4 term but not the omega^2 term',
  'positive_class_theorem':'If M0 is positive definite and Z is positive semidefinite and nonzero, then adj(M0) is positive definite and tr(adj(M0) Z)>0. Therefore D1>0 and det(M0-omega^2 Z) remains frequency dependent.',
  'consequence':'Within this ordinary positive two-auxiliary class, exact removal of the auxiliary frequency denominator requires Z=0. A nontrivial cancellation must use a genuinely constrained/gauge-degenerate or otherwise non-positive intermediate structure and needs an explicit DOF/ghost analysis.',
  'scope':'real symmetric 2x2 auxiliary block with M0>0 and Z>=0; not a theorem against Dirac-degenerate gauge systems, larger exact cancellations, branch-changing theories, or retarded/nonlocal completions',
  'next_step':'If CI passes, formulate the smallest genuinely Dirac-degenerate auxiliary action and compute its primary/secondary constraints rather than attempting further positive-matrix pole cancellations.'
}

print('RTK_ROUTE_B_TWO_AUXILIARY_POSITIVE_CANCELLATION_GATE_PASS', json.dumps(out, sort_keys=True))
