#!/usr/bin/env python3
"""C8 correction theorem: the complete TT-safe scalar grad-K basis.

This file supersedes the *broad* interpretation of
`route_b_gradK_tensor_null_gate.py`.  That earlier gate considered the scalar
basis generated by

  O_T = D_l K^i_j D^l K^j_i,
  O_K = D_i K D^i K,
  O_D = D_i K^i_j D_k K^{kj},

and correctly found that, inside that restricted three-operator choice, the
coefficient of O_T vanishes on the exact RTK branch only at R=2.

However the one-spatial-derivative quadratic action also admits the cross
contraction

  O_X = D_i K D_j K^{ij}.

At scalar quadratic order around flat FLRW, with

  A = dot(zeta)-H n,
  q = p^2 psi,
  delta K = 3A+q,
  D_j delta K^j_i ~ ik_i(A+q),

the TT-safe operators map to the general scalar form

  p^2 [ U A^2 + 2 V A q + W q^2 ]

as

  O_K -> (U,V,W)=(9,3,1),
  O_D -> (1,1,1),
  O_X -> (3,2,1).

Their 3x3 map has determinant -4, so these three TT-safe operators alone span
*every* scalar triple (U,V,W).  No O_T term is required.

The inverse map is

  c_K = (U-2V+W)/4,
  c_D = (U-6V+9W)/4,
  c_X = (-U+4V-3W)/2.

For the exact RTK pointwise branch U W=V^2, define r=V/W.  Then

  U=r^2 W,
  c_K=W(r-1)^2/4,
  c_D=W(r-3)^2/4,
  c_X=-W(r-1)(r-3)/2.

Equivalently the whole correction is the single square

  W [ ((r-1)/2) D_i K + ((3-r)/2) D_j K^j_i ]^2.

For a TT perturbation, delta K=0 and D_j delta K^j_i=0, so this operator
vanishes identically in the TT sector at quadratic order.  It also vanishes in
a strictly static K_ij=0 sector.

Therefore the exact scalar RTK pointwise grad-K escape can be both static-safe
and tensor-speed-safe at quadratic flat-FLRW level for arbitrary r.  The
previous R=2 condition remains true only for the restricted basis that omitted
O_X and must not be quoted as a full grad-K no-go.

This correction does NOT solve the all-epoch fixed-action problem.  The
already-independent fixed-Wilson theorem remains: constant U,V,W would force
M_K to be constant, contrary to production.  The next problem is whether one
fixed local action with state/invariant-dependent coefficient functions can
produce W(a) and r(a) without epoch-by-epoch fitting, while preserving DOF,
stability, PPN/Newton behavior and a controlled EFT cutoff.
"""

import json
import sympy as sp

U,V,W,r=sp.symbols('U V W r', finite=True, real=True)
cK,cD,cX=sp.symbols('cK cD cX', finite=True, real=True)

OK=sp.Matrix([9,3,1])
OD=sp.Matrix([1,1,1])
OX=sp.Matrix([3,2,1])
M=sp.Matrix.hstack(OK,OD,OX)
assert M.det()==-4

sol=M.LUsolve(sp.Matrix([U,V,W]))
assert sp.simplify(sol[0]-(U-2*V+W)/4)==0
assert sp.simplify(sol[1]-(U-6*V+9*W)/4)==0
assert sp.simplify(sol[2]-(-U+4*V-3*W)/2)==0

# Exact RTK rank-one branch U=r^2 W, V=r W.
rtk={U:r**2*W,V:r*W}
cK_r=sp.factor(sol[0].subs(rtk))
cD_r=sp.factor(sol[1].subs(rtk))
cX_r=sp.factor(sol[2].subs(rtk))
assert sp.simplify(cK_r-W*(r-1)**2/4)==0
assert sp.simplify(cD_r-W*(r-3)**2/4)==0
assert sp.simplify(cX_r+W*(r-1)*(r-3)/2)==0

# Direct single-square identity in scalar variables.
A,q=sp.symbols('A q', real=True)
alpha=(r-1)/2
beta=(3-r)/2
trace=3*A+q
div=A+q
combo=sp.expand(alpha*trace+beta*div)
assert sp.simplify(combo-(r*A+q))==0
square=sp.expand(W*combo**2)
target=sp.expand(W*(r*A+q)**2)
assert sp.simplify(square-target)==0

# Expanded operator coefficients reproduce the inverse map.
expanded=sp.expand(W*(alpha*trace+beta*div)**2)
# Coefficients of trace^2, div^2, trace*div are W alpha^2, W beta^2,
# 2 W alpha beta respectively, matching cK,cD,cX.
assert sp.simplify(W*alpha**2-cK_r)==0
assert sp.simplify(W*beta**2-cD_r)==0
assert sp.simplify(2*W*alpha*beta-cX_r)==0

out={
  'classification':'RTK_ROUTE_B_GRADK_FULL_TTSAFE_BASIS_GATE_PASS',
  'correction':{
    'supersedes_broad_interpretation_of':'route_b_gradK_tensor_null_gate.py',
    'restricted_result_retained':'R=2 is the tensor-null condition only in the restricted {O_T,O_K,O_D} representation with O_X omitted',
    'reason':'O_X=D_i K D_j K^{ij} is an allowed independent scalar contraction and is TT-null'
  },
  'tt_safe_basis':{
    'O_K':'D_i K D^i K -> (U,V,W)=(9,3,1)',
    'O_D':'D_i K^i_j D_k K^{kj} -> (1,1,1)',
    'O_X':'D_i K D_j K^{ij} -> (3,2,1)',
    'map_determinant':'-4',
    'inverse':{
      'c_K':'(U-2V+W)/4',
      'c_D':'(U-6V+9W)/4',
      'c_X':'(-U+4V-3W)/2'
    }
  },
  'exact_rtk_rank_one_branch':{
    'definition':'r=V/W, U=r^2 W',
    'c_K':'W(r-1)^2/4',
    'c_D':'W(r-3)^2/4',
    'c_X':'-W(r-1)(r-3)/2',
    'single_square':'W[((r-1)/2) D_i K + ((3-r)/2) D_j K^j_i]^2'
  },
  'static_sector':'vanishes when K_ij=0',
  'tt_sector':'vanishes identically because delta K=0 and D_j delta K^j_i=0 for transverse-traceless tensors',
  'theorem':'At quadratic flat-FLRW level, the exact RTK scalar pointwise grad-K correction can be represented entirely by operators that vanish in both the strictly static and TT sectors. The earlier special R=2 tensor-null condition is not a full-basis obstruction.',
  'unchanged_negative_result':'The constant-Wilson all-epoch obstruction remains valid because it follows from the required U,V,W themselves, not from a particular invariant basis.',
  'non_claims':[
    'not yet an all-epoch fixed state-function action',
    'not a PPN/Newton proof beyond the strictly static K_ij=0 statement',
    'not a nonlinear or compact-object theorem',
    'not a DOF/degeneracy proof',
    'not a strong-coupling or radiative-stability proof'
  ],
  'next_step':'Construct W and r as fixed local functions of Khronon/geometric invariants and test all epochs, DOF/stability, PPN/Newton, compact objects and EFT cutoff.'
}
print('RTK_ROUTE_B_GRADK_FULL_TTSAFE_BASIS_GATE_PASS',json.dumps(out,sort_keys=True))
