#!/usr/bin/env python3
"""C8 same-action O(2) static/Newton/gamma gate for U(1)+RTK IR v3.

External equations are the nonprojectable U(1) PPN O(2) system of
Lin-Mukohyama-Wang-Zhu, arXiv:1310.6666, Eqs. (5.24),(5.25),(5.28),(5.29).

Project input established by the preceding static-lapse bridge:
for the explicit rolling RTK mixed operator, the pure-lapse quadratic action is
identical to a beta0_eff=2 acceleration term, while S_mix has no direct A source
and its pure spatial-metric variation starts beyond O(2). Therefore the complete
O(2) static equations are obtained from those literature equations by using
beta0_eff=2 in the Hamiltonian/lapse equation only, with the same A and spatial
dynamical equations.

Frozen IR representative:
 a1=1, a2=0, kappa=G/G_N=1, sigma1=sigma2=0,
 gamma1=-1, beta0_bare=0, lambda_HL=1,
 plus explicit S_mix giving beta0_eff=2 at quadratic static order.

This certifies Newtonian/O(2) normalization and gamma_PPN only. It explicitly
does NOT certify beta_PPN or the full PPN vector/preferred-frame sector because
S_mix differs from a beta0 term starting at cubic weak-field action order.
"""
import json
import sympy as sp

a1,a2,kappa,sigma2,gamma1,beta_eff=sp.symbols(
    'a1 a2 kappa sigma2 gamma1 beta_eff', finite=True, real=True)
gamma,f=sp.symbols('gamma f', finite=True, real=True)

vals={a1:1,a2:0,kappa:1,sigma2:0,gamma1:-1,beta_eff:2}

# Eq. (5.25), with beta0 replaced by the proven quadratic static effective
# coefficient supplied by explicit S_mix.
den=2*beta_eff*a1-4*gamma1*a2-sigma2
num=2*beta_eff+4*gamma1*gamma+4*kappa
f_expr=sp.factor(num/den)
f_v3=sp.simplify(f_expr.subs(vals))
assert sp.simplify(f_v3-(2-gamma))==0

# Eq. (5.28): spatial dynamical equation at O(2).
eq_dyn=sp.expand(f + gamma1*(gamma+a2*f) - gamma1*(1-a1*f))
eq_dyn_v3=sp.simplify(eq_dyn.subs(vals).subs(f,f_v3))
assert sp.simplify(eq_dyn_v3-(1-gamma))==0

# Eq. (5.29): A-constraint at O(2).
eq_A=sp.expand(4*kappa*a1-4*(gamma+a2*f)+sigma2*(1-a1*f))
eq_A_v3=sp.simplify(eq_A.subs(vals).subs(f,f_v3))
assert sp.simplify(eq_A_v3-(4-4*gamma))==0

sol_gamma_dyn=sp.solve(sp.Eq(eq_dyn_v3,0),gamma)
sol_gamma_A=sp.solve(sp.Eq(eq_A_v3,0),gamma)
assert sol_gamma_dyn==[1] and sol_gamma_A==[1]
gamma_sol=sp.Integer(1)
f_sol=sp.simplify(f_v3.subs(gamma,gamma_sol))
assert f_sol==1

# Eq. (5.24) then gives A_2=f U, hence A_2=U.
# Check the raw Laplace coefficients at gamma=1.
lhs_H=(2*beta_eff*a1-4*gamma1*a2-sigma2).subs(vals)
rhs_H=(2*(2*gamma1*gamma+beta_eff+2*kappa)).subs(vals).subs(gamma,gamma_sol)
assert sp.simplify(lhs_H-rhs_H)==0 and lhs_H==4

# Eq. (5.43) compatibility at the same O(2) effective coefficient.
eq543=beta_eff*(a1**2*kappa*gamma1+1)+2*kappa*(a1*gamma1+1)**2
assert sp.simplify(eq543.subs(vals))==0

# kappa is defined in the paper as G/G_N.
G,GN=sp.symbols('G G_N', positive=True, finite=True, real=True)
assert sp.solve(sp.Eq(G/GN,1),GN)==[G]

out={
  'classification':'RTK_ROUTE_B_U1_STATIC_O2_NEWTON_GAMMA_GATE_PASS',
  'representative':'research/RTK_C8_U1_FIXED_IR_REPRESENTATIVE_v3.json',
  'external_equations':'arXiv:1310.6666 Eqs.(5.24),(5.25),(5.28),(5.29); kappa=G/G_N',
  'same_action_bridge':'explicit S_mix is equivalent to beta0_eff=2 only in the quadratic pure-lapse static action; it remains explicit in the action and beta0_bare stays zero',
  'f_solution':'1',
  'A2_solution':'A_2=U',
  'gamma_PPN_O2':'1',
  'newton_normalization':'kappa=G/G_N=1, hence G_N=G on the frozen representative',
  'Hamiltonian_O2_laplace_coefficients':'lhs=rhs=4 in the literature normalization',
  'Eq543_O2_consistency':'0=0 at a1=kappa=1, gamma1=-1, beta0_eff=2',
  'status_scope':'STATIC_NEWTON_GAMMA_GREEN_O2_ONLY',
  'non_claims':[
    'does not certify beta_PPN: explicit S_mix differs from beta0_eff=2 at cubic action order by -2 M_Pl^2 n(Dn)^2',
    'does not certify alpha1 or alpha2 because time-dependent/vector O(3) equations have not been rederived with explicit S_mix',
    'does not import the published pure-U1 full PPN result as a full-action result',
    'does not establish nonlinear compact-object behavior, radiative stability, UV tensor dispersion, or EFT cutoff'
  ],
  'next_gate':'derive the O(4) static equations generated by the explicit S_mix cubic mismatch and determine the correction to beta_PPN on the same v3 action; separately rederive O(3) vector/preferred-frame equations before alpha1/alpha2 claims'
}
open('u1_static_o2_newton_gamma_result.json','w').write(json.dumps(out,indent=2,sort_keys=True)+'\n')
print(out['classification'],json.dumps(out,sort_keys=True))
