#!/usr/bin/env python3
"""C8 exact theorem: pointwise grad-K escape versus one fixed constant-Wilson action.

We extend the controlled flat-FLRW scalar constraint system by the most general
quadratic scalar contribution generated by one spatial derivative acting on
extrinsic curvature,

    y [ U A^2 + 2 V A q + W q^2 ],

where y=p^2, A=dot(zeta)-H n, q=y psi.  The common spatially covariant
quadratic invariants

    O_T = D_l K^i_j D^l K^j_i,
    O_K = D_i K D^i K,
    O_D = D_i K^i_j D_k K^{kj},

span arbitrary scalar (U,V,W) at quadratic order around flat FLRW, so the
pointwise algebra below is not a shortage-of-basis artifact.

Exact lapse+shift elimination and exact matching to the RTK target

    K/(2 H^2) * (1 + y/MK^2)

requires

    U W = V^2,
    V/W = (6 H^2 M_*^2 - K)/(4 H^2 M_*^2),
    W = 2 H^2 M_*^4/(K MK^2).

Thus a pointwise static-safe solution exists.  However if U,V,W are constants
of one fixed simple action over an interval of FLRW epochs, then

    R := K/(H^2 M_*^2) = 6 - 4 V/W

is constant, and the W equation implies

    MK^2 = 2 M_*^2/(R W) = constant.

The production DBI-Khronon scale is

    x=x0/a^3,
    s=sqrt(1+lambda_D x^2),
    MK=mu_K (1+x/s) s^(3/2) = mu_K sqrt(s) (s+x).

For x>0 and lambda_D>0, ds/dx=lambda_D x/s>0 and therefore

    d(MK/mu_K)/dx
      = sqrt(s) (1+ds/dx) + (s+x) ds/dx/(2 sqrt(s)) > 0.

Since x changes with a, MK is not constant on any nontrivial epoch interval.
Hence no constant-Wilson member of this grad-K scalar class can reproduce the
exact production RTK kinetic factor for all epochs.

Scope: this is NOT a no-go for fixed state-dependent coefficient functions,
K-dressed operators, auxiliary constrained fields, nonminimal matter maps, or
a broader spatially covariant/covariant completion.  It is the precise gate
between a pointwise quadratic solution and a constant-coefficient fixed action.
"""

import json
import sympy as sp

# Background and perturbation symbols.
y,H,M2,K,MK2 = sp.symbols('y H M2 K MK2', positive=True, finite=True, real=True)
U,V,W = sp.symbols('U V W', finite=True, real=True)
d,z,n,q = sp.symbols('d z n q', real=True)
A = d-H*n

# Established EH+clock scalar kernel plus the general static-safe grad-K scalar
# quadratic form. M2 means M_*^2, so M2**2 means M_*^4.
L = (
    -3*M2*A**2
    + sp.Rational(1,2)*K*n**2
    + 2*M2*y*n*z
    + M2*y*z**2
    - 2*M2*A*q
    + y*(U*A**2 + 2*V*A*q + W*q**2)
)

sol = sp.solve([sp.diff(L,q), sp.diff(L,n)], [q,n], dict=True, simplify=False)
assert len(sol) == 1
Lred = sp.factor(sp.simplify(L.subs(sol[0])))
kin = sp.factor(sp.diff(Lred,d,2)/2)
target = sp.factor(K/(2*H**2)*(1+y/MK2))
num = sp.factor(sp.together(kin-target).as_numer_denom()[0])
poly = sp.Poly(num,y)
assert poly.degree() == 3
c1 = sp.factor(poly.coeff_monomial(y))
c2 = sp.factor(poly.coeff_monomial(y**2))
c3 = sp.factor(poly.coeff_monomial(y**3))

# Exact pointwise matching identities.
W_req = sp.factor(2*H**2*M2**2/(K*MK2))
ratio_req = sp.factor((6*H**2*M2-K)/(4*H**2*M2))
assert sp.simplify(c1.subs(W,W_req)) == 0
assert sp.simplify(c2.subs({W:W_req,V:ratio_req*W_req})) == 0
assert sp.factor(c3/(2*H**2*K)) == -(U*W-V**2)

# Rank-one pointwise branch.
V_req = sp.factor(ratio_req*W_req)
U_req = sp.factor(V_req**2/W_req)
assert sp.simplify(kin.subs({U:U_req,V:V_req,W:W_req})-target) == 0

# The standard three grad-K invariants span arbitrary scalar U,V,W:
# O_T -> (3,1,1), O_K -> (9,3,1), O_D -> (1,1,1), where the tuple is
# (U,V,W).  Invert the map exactly.
cT,cK,cD = sp.symbols('cT cK cD', real=True)
map_eq = {
    U: 3*cT + 9*cK + cD,
    V: cT + 3*cK + cD,
    W: cT + cK + cD,
}
mat = sp.Matrix([[3,9,1],[1,3,1],[1,1,1]])
assert mat.det() != 0
inv = sp.solve([
    sp.Eq(U,map_eq[U]), sp.Eq(V,map_eq[V]), sp.Eq(W,map_eq[W])
], [cT,cK,cD], dict=True)
assert len(inv)==1
assert sp.simplify(inv[0][cT]-(U-4*V+3*W)/2)==0
assert sp.simplify(inv[0][cK]-(V-W)/2)==0
assert sp.simplify(inv[0][cD]-(3*V-U)/2)==0

# Constant-Wilson obstruction.  For constants V/W and W, exact matching makes
# R=K/(H^2 M_*^2) constant and then forces MK^2 constant.
R = sp.symbols('R', positive=True, finite=True, real=True)
R_from_ratio = sp.factor(6-4*V/W)
W_via_R = sp.factor(W_req.subs(K,R*H**2*M2))
assert sp.simplify(W_via_R-2*M2/(R*MK2))==0
MK2_forced = sp.factor(2*M2/(R*W))

# Production MK monotonicity with exact positive-domain algebra.
x,lam,mu = sp.symbols('x lam mu', positive=True, finite=True, real=True)
s = sp.sqrt(1+lam*x**2)
MK = sp.factor(mu*sp.sqrt(s)*(s+x))
dsdx = sp.factor(sp.diff(s,x))
dMKdx = sp.factor(sp.diff(MK,x)/mu)
positive_form = sp.sqrt(s)*(1+dsdx) + (s+x)*dsdx/(2*sp.sqrt(s))
assert sp.simplify(dMKdx-positive_form)==0
# Every factor/addend in positive_form is strictly positive for x,lam>0.
assert sp.simplify(dsdx-lam*x/s)==0

out = {
    'classification':'RTK_ROUTE_B_GRADK_FIXED_WILSON_GATE_PASS',
    'pointwise_match':{
        'UW_minus_V2':'0',
        'V_over_W':'(6 H^2 M_*^2-K)/(4 H^2 M_*^2)',
        'W':'2 H^2 M_*^4/(K M_K^2)',
        'status':'EXISTS_POINTWISE'
    },
    'covariant_scalar_basis':{
        'O_T':'D_l K^i_j D^l K^j_i -> (U,V,W)=(3,1,1)',
        'O_K':'D_i K D^i K -> (9,3,1)',
        'O_D':'D_i K^i_j D_k K^{kj} -> (1,1,1)',
        'determinant':str(mat.det()),
        'inverse':{
            'cT':'(U-4V+3W)/2',
            'cK':'(V-W)/2',
            'cD':'(3V-U)/2'
        }
    },
    'constant_wilson_obstruction':{
        'R_definition':'K/(H^2 M_*^2)',
        'R_forced_by_constant_ratio':'6-4 V/W',
        'W_after_R_substitution':'2 M_*^2/(R M_K^2)',
        'MK2_forced_if_R_W_constant':'2 M_*^2/(R W)',
        'production_MK':'mu_K sqrt(s) (s+x), s=sqrt(1+lambda_D x^2), x=x0/a^3',
        'production_monotonicity':'dM_K/dx > 0 for x>0, lambda_D>0',
        'conclusion':'NO_EXACT_ALL_EPOCH_CONSTANT_WILSON_GRADK_SOLUTION'
    },
    'theorem':'The full scalar grad-K basis can realize the exact RTK kernel at one FLRW state, but one constant coefficient tuple cannot realize the evolving production M_K(a) over a nontrivial epoch interval.',
    'non_claims':[
        'not a no-go for fixed coefficient functions of a Khronon state invariant',
        'not a no-go for K- or curvature-dressed grad-K operators',
        'not a no-go for auxiliary constrained fields',
        'not a no-go for nonminimal/disformal matter frames',
        'not a PPN/GW/compact-object/strong-coupling theorem'
    ],
    'next_step':'Test the smallest fixed state-dependent or background-invariant dressing that generates the required U(a),V(a),W(a) from one action without epoch-by-epoch fitting.'
}
print('RTK_ROUTE_B_GRADK_FIXED_WILSON_GATE_PASS',json.dumps(out,sort_keys=True))
